export default {
    home: 'Home',
    about:"About",
    team:"The Team",
    store:"Online Store",
    homeWelcome: "Hello to Home",
    contact:"Contact",
    product:"Product",
    homePageSub:"Your gross seller of jewelry and accessoires for more than 10 years.",
    value01:"Agility",
    value02:"Commitment",
    value03:"Personality",
    value01text:"pharetra erat vel, pulvinar sapien. Cras tincidunt felis purus, eget scelerisque lectus interdum sit amet.",
    value02text:"pharetra erat vel, pulvinar sapien. Cras tincidunt felis purus, eget scelerisque lectus interdum sit amet.",
    value03text:"pharetra erat vel, pulvinar sapien. Cras tincidunt felis purus, eget scelerisque lectus interdum sit amet.",
    aboutText:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas consectetur maximus elit, eu tempus nibh volutpat vel. Sed vel magna a turpis vulputate fringilla ut ac mi. Duis faucibus velit nec porttitor bibendum. Suspendisse posuere nisl eget massa maximus bibendum. Nullam at enim ut sapien luctus ultricies et ut turpis. Donec dapibus ullamcorper sem, hendrerit vehicula felis sagittis nec. Duis vehicula magna vel mi mollis condimentum. Nullam et pharetra lacus. Sed rhoncus, nisi quis tincidunt venenatis, sem eros efficitur dolor, et suscipit odio purus a lacus. Cras dictum nisi nec mauris venenatis suscipit quis quis risus. Nunc ac dolor porttitor dolor rhoncus viverra. Cras in diam ex. Vestibulum nec nisl rutrum elit tempus ultrices. In sollicitudin erat non leo bibendum, eget mattis magna suscipit.",
    contactblurb:"Get in touch with Le Bijou!",
    formName:"Name",
    formLastName:"Last Name",
    formEmail:"Email",
    formCorp:"Business",
    formTextArea:"Write your message in here",
    sendButton:"Send"

};